export default {
    links:[
        {
            to:"/addmine",
            content:"添加矿场"
        },
        {
            to:"/minelist",
            content:"矿场列表"
        },
        {
            to:"/ammeterlevel",
            content:"添加电表级别"
        },
        {
            to:"/ammeterlist",
            content:"电表级别列表"
        },
        {
            to:"/recording",
            content:"维修添加记录"
        },
        {
            to:"/recordinglist",
            content:"添加记录列表"
        },
        {
            to:"/machinenumber",
            content:"机号"
        },
        {
            to:"/addframe",
            content:"机架"
        },
        {
            to:"/adduser",
            content:"添加用户"
        },
        {
            to:"/userlist",
            content:"用户列表"
        },
        {
            to:"/work",
            content:"维修添加记录"
        },
        {
            to:"/framelist",
            content:"机架列表"
        },
    ]
}